### PR TITLE
Update libgit2 to v1.3.0

### PR DESCRIPTION
**Pull request by jairbubbles**
*It's not exactly v1.3 as @ethomson didn't tag yet*

- Update libgit2 to move along with https://github.com/libgit2/libgit2sharp/pull/1908

### CODE REVIEW

**Comment by jairbubbles** [comment]
Let me know @bording if it's ok for you to merge this (and publish a prerelease package).

**Comment by bording** [comment]
Based on the latest commits on the libgit2 repo, it seems like the tagged 1.3.0 release is imminent, so at this point I think I'd prefer to wait for the actual release at this point.

**Comment by jairbubbles** [comment]
Thanks @ethomson  I updated to the real v1.3.0 ☺

**Review by bording — APPROVED** [review]

**Comment by bording** [comment]
2.0.315-alpha.0.4 has been published.

**Pull request merged**
