### PR TITLE
Update to 6aa06b6

### PR DESCRIPTION
**Pull request by carlosmn**
https://github.com/libgit2/libgit2/compare/a27f31...6aa06b6

This includes the tree parsing perf improvements.

### CODE REVIEW

**Comment by nulltoken** [comment]
@carlosmn Still suffering from some identity/signature crisis, huh? :stuck_out_tongue_winking_eye:

**Comment by carlosmn** [comment]
Updated the signature and the lg2 version to the latest tip.

**Comment by nulltoken** [comment]
Maybe should https://github.com/libgit2/libgit2sharp/pull/1237 be updated to benefit from this one?

**Comment by carlosmn** [comment]
Yes, that's the plan. We'll actually also want the reset fix which landed just after I sent this in, so I'll send off another PR to this repo soon.

**Comment by carlosmn** [comment]
Oops, I completely forgot that I'd already updated this PR for that.

**Comment by nulltoken** [comment]
So is this one good to go?

**Pull request merged**
