### PR TITLE
Update libgit2 to v1.2.0

### PR DESCRIPTION
**Pull request by jairbubbles**
- Remove compilation hack as https://github.com/libgit2/libgit2/pull/5994 is now included
- Set `HTTPS` to `OpenSSL-Dynamic`

### CODE REVIEW

**Comment by bording** [comment]
As part of this PR, let's go ahead and update https://github.com/libgit2/libgit2sharp.nativebinaries/blob/master/build.libgit2.sh#L14 to be `OpenSSL-Dynamic` instead of `OFF`.

**Comment by jairbubbles** [comment]
Sure I'll give it a shot!

**Comment by jairbubbles** [comment]
I updated the value blindly, looks like it's all green!

**Comment by ethomson** [comment]
I'm hopeful that this is a better outcome than the managed transport was.  🤞

**Review by bording — APPROVED** [review]

**Comment by bording** [comment]
> I'm hopeful that this is a better outcome than the managed transport was. 🤞

@ethomson Would a similar approach for SSH support be possible? Being able to optionally support SSH and not need to worry about bundling libraries for it would be great.

**Comment by bording** [comment]
2.0.315-alpha.0.2 has been uploaded to nuget.org

**Comment by ethomson** [comment]
>  Would a similar approach for SSH support be possible? Being able to optionally support SSH and not need to worry about bundling libraries for it would be great.

Possible, yes - but I don't have an estimate of the amount of work.  I'm not super familiar with libssh2 or our use of it.  I think that my big hesitation is that libssh2 doesn't appear to be a particular amazing library and hasn't seen many updates lately, IIRC.  I worry that it would be a decent amount of effort for a disappointing result.

**Comment by bording** [comment]
> > Would a similar approach for SSH support be possible? Being able to optionally support SSH and not need to worry about bundling libraries for it would be great.
> 
> Possible, yes - but I don't have an estimate of the amount of work. I'm not super familiar with libssh2 or our use of it. I think that my big hesitation is that libssh2 doesn't appear to be a particular amazing library and hasn't seen many updates lately, IIRC. I worry that it would be a decent amount of effort for a disappointing result.

That all makes sense. It was just something I was wondering about since it seems like the majority of the LibGit2Sharp forks and alternate NuGet packages on nuget.org are related to SSH support.

**Pull request merged**
