### PR TITLE
Update libgit2 to v1.8.1

### PR DESCRIPTION
**Pull request by parnic**

### CODE REVIEW

**Comment by DefaultRyan** [comment]
Would love to see this approved. This is needed to fix https://github.com/libgit2/libgit2sharp/issues/2090 which breaks libgit2sharp on repos that enabled index.skipHash.

**Comment by DefaultRyan** [comment]
@bording Is this something you'd be able to look into?

**Comment by evya-dev** [comment]
This merge would be appreciated to solve the following issue in libgit2Sharp repo:

https://github.com/libgit2/libgit2sharp/issues/2109

**Comment by DefaultRyan** [comment]
@ethomson has been semi-active recently. Is this something they'd be able to look at?

**Comment by bording** [comment]
Thanks for opening the PR. It's now superseded by #162 which updates to v1.8.4.

**Pull request closed without merging**
