### PR TITLE
Support package.json magic

### LINKED ISSUE #39: Build NuGet v3/dotnet cli compatible package
The new NuGet v3/dotnet cli tooling now has built-in support for distributing native binaries.
It will automatically load relevant libraries without the need to do anything special, it's not even necessary anymore to have a build task to copy them around, everything just works.

This is used for example by the https://www.nuget.org/packages/Libuv/ package for Kestrel.

Making use of this is trivial: Just place the libraries in a special folder structure and NuGet automatically picks them up.

Currently, the binaries live here:
```
libgit2/linux/x86_64/libgit2-381caf5.so  
libgit2/osx/libgit2-381caf5.dylib  
libgit2/win32/x64/git2-381caf5.dll  
libgit2/win32/x86/git2-381caf5.dll  
```

All that needs to be done is to move them here:
```
runtimes/linux-x64/native/libgit2-381caf5.so
runtimes/osx/native/libgit2-381caf5.dylib
runtimes/win7-x64/native/git2-381caf5.dll
runtimes/win7-x86/native/git2-381caf5.dll
```

I tried to create a PR but couldn't quite figure out how all the build scripts etc. work and it seems hard to test without direct access to the build servers.

Therefore I repackaged the existing LibGit2Sharp.NativeBinaries package with the new folder structure: https://www.nuget.org/packages/LibGit2Sharp.NativeBinaries-dotnet/ as an example. I tested that package and it works nicely.

Do you think you could update the build scripts to output nuget v3 compatible packages? Should just be a matter of adjusting the paths and then updating the old-school build.props so existing users don't break.

Let me know if you need a hand, happy to help out.

### PR DESCRIPTION
**Pull request by ethomson**
Apparently .NET Core type builds will:

a) eschew msbuild magic, and
b) place native binaries according to some directory hierarchy conventions.

Fixes #39

### CODE REVIEW

**Comment by bording** [comment]
I believe that most of the other scripts have references to the libgit2 path that will also need to be updated to make sure everything is in the right place when the package is built.

**Comment by ethomson** [comment]
The tragic disappointment of this change means, of course, that we'll reopen https://github.com/libgit2/libgit2sharp/issues/1170.  HA HA.

@bording did you happen to file a bug against mono?

**Comment by bording** [comment]
> The tragic disappointment of this change means, of course, that we'll reopen libgit2/libgit2sharp#1170. HA HA.

I randomly was thinking about this the other day, and realized this exact thing, but apparently forgot about it again before I had a chance to mention it. :disappointed: 

Unfortunately, I never found the time to actually set up a Bugzilla account at https://bugzilla.xamarin.com and go through the process of getting a decent but report filed. :cry: 

So, support nuget3-style native dependencies, or mono?

**Comment by bording** [comment]
Actually wait, if the props file and dllmap file still use the lib folder, won't that still put things in the right place?

**Comment by bording** [comment]
The question is what sort of change have to happen to the actual loading code to make this work in both scenarios? I'm not sure how you're supposed to be referencing these native libraries from managed code when using this .NET Core runtimes magic.

**Comment by ethomson** [comment]
> Actually wait, if the props file and dllmap file still use the lib folder, won't that still put things in the right place?

Hmm.  That would be nice.  That seems reasonable.  I was hoping to get a 1:1 mapping between what's in the nuget package and what ends up on the filesystem, but there's no need for that, I suppose (except my ever-decreasing sanity.)

**Comment by ethomson** [comment]
> The question is what sort of change have to happen to the actual loading code to make this work in both scenarios? I'm not sure how you're supposed to be referencing these native libraries from managed code when using this .NET Core runtimes magic.

There shouldn't be any changes, if I understand correctly.  .NET 4.whatever will still run msbuild as it used to.  .NET Core won't run msbuild at all, so it will look for the magic paths.

**Comment by bording** [comment]
> Hmm. That would be nice. That seems reasonable. I was hoping to get a 1:1 mapping between what's in the nuget package and what ends up on the filesystem, but there's no need for that, I suppose (except my ever-decreasing sanity.)

That also would have required changes [here](https://github.com/libgit2/libgit2sharp/blob/3febf8d0481ddca01d59d3e80d4af0ca8c26c240/LibGit2Sharp/GlobalSettings.cs#L27-L27) to make it look somewhere other than 'lib'.

> There shouldn't be any changes, if I understand correctly

So .NET Core must understand the runtime ids that are in the nuget package, and then uses those paths when processing the `DllImport` attribute. If that's how it works, then yeah, it seems like it should work in both cases.

Maybe one day in the future this will be supported everywhere, and the extra path manipulation code could be removed, and this could all be simplified. Hah!

**Comment by ethomson** [comment]
Okay, well, some manual testing suggests that this is working for .NET 4 (not .NET Core) on Windows.  I'm going to merge this so that I can spin an actual native nuget package (not a prerelease).

If this is terrible then of course we can revert it.

**Pull request merged**
