### PR TITLE
Disable PackageAnalysis mode while packing

### PR DESCRIPTION
**Pull request by nulltoken**
Included changes trigger the following output

```
PS F:\libgit2sharp.nativebinaries> .\download.build.artifacts.and.package.ps1
Creating temporary folder at "C:\Users\ntk\AppData\Local\Temp\uwdquwfw.pdf"
Retrieving LibGit2Sharp.NativeBinaries latest CI statuses of "master"
-> Get https://api.github.com/repos/libgit2/libgit2sharp.nativebinaries/commits/master/statuses
Retrieving AppVeyor build "1.0.106"
-> Get https://ci.appveyor.com/api/projects/libgit2/libgit2sharp-nativebinaries/build/1.0.106
Retrieving AppVeyor job "477c461168fy0o28" artifacts
-> Get https://ci.appveyor.com/api/buildjobs/477c461168fy0o28/artifacts
Downloading "LibGit2Sharp.NativeBinaries.1.0.106.nupkg"
-> Get https://ci.appveyor.com/api/buildjobs/477c461168fy0o28/artifacts/LibGit2Sharp.NativeBinaries.1.0.106.nupkg
Retrieving Travis build "87090683"
-> Get https://api.travis-ci.org/builds/87090683
Downloading "binaries-linux-91.zip"
-> Get https://dl.bintray.com/libgit2/compiled-binaries/binaries-linux-91.zip
Downloading "binaries-osx-91.zip"
-> Get https://dl.bintray.com/libgit2/compiled-binaries/binaries-osx-91.zip
Build artifacts have been downloaded at "C:\Users\ntk\AppData\Local\Temp\uwdquwfw.pdf"
Extracting build artifacts
Including non Windows build artifacts
Building final NuGet package
Attempting to build package from 'LibGit2Sharp.NativeBinaries.nuspec'.

Id: LibGit2Sharp.NativeBinaries
Version: 1.0.106
Authors: LibGit2Sharp contributors
Description: Native binaries for LibGit2Sharp
License Url: https://raw.githubusercontent.com/libgit2/libgit2/master/COPYING
Project Url: https://github.com/libgit2/libgit2sharp.nativebinaries
Dependencies: None

Added file '[Content_Types].xml'.
Added file 'build\LibGit2Sharp.NativeBinaries.props'.
Added file 'libgit2\libgit2.license.txt'.
Added file 'libgit2\libgit2_filename.txt'.
Added file 'libgit2\libgit2_hash.txt'.
Added file 'libgit2\LibGit2Sharp.dll.config'.
Added file 'libgit2\linux\amd64\libgit2-821131f.so'.
Added file 'libgit2\osx\libgit2-821131f.dylib'.
Added file 'libgit2\windows\amd64\git2-821131f.dll'.
Added file 'libgit2\windows\amd64\git2-821131f.pdb'.
Added file 'libgit2\windows\x86\git2-821131f.dll'.
Added file 'libgit2\windows\x86\git2-821131f.pdb'.

Successfully created package 'C:\Users\ntk\AppData\Local\Temp\uwdquwfw.pdf\LibGit2Sharp.NativeBinaries.1.0.106.nupkg'.
```

### CODE REVIEW

**Comment by bording** [comment]
Using the detailed Verbosity level is a nice tweak!

It does point out one other change that might be worth making though. 

> Added file '[Content_Types].xml'.

Looks like you might want to delete all the metadata bits that get put into the extracted package folder before repacking it:

- `_rels\`
- `package\`
- `[Content_Types].xml`

**Comment by bording** [comment]
Also, maybe you could copy the final package to $root instead, which would let you clean up the temp folder that currently gets left behind. That would also let you have a single Remove-Item call without needing to clean up all of the other extracted folders separately.

**Comment by nulltoken** [comment]
@bording Good catch! I've updated the PR to also take this into account.

**Comment by nulltoken** [comment]
> Also, maybe you could copy the final package to $root instead, which would let you clean up the temp folder that currently gets left behind. That would also let you have a single Remove-Item call without needing to clean up all of the other extracted folders separately.

I haven't read this comment before pushing up this last commit. Let me see what I can do about this.

**Comment by nulltoken** [comment]
>> Also, maybe you could copy the final package to $root instead, which would let you clean up the temp folder that currently gets left behind. That would also let you have a single Remove-Item call without needing to clean up all of the other extracted folders separately.

> I haven't read this comment before pushing up this last commit. Let me see what I can do about this.

Better?

**Comment by bording** [comment]
The only other thing I see is that you could get rid of the Remove-Item calls on lines 115, 117, and 119 since you're now deleting the entire temp folder.

Otherwise, :+1:

**Comment by nulltoken** [comment]
> The only other thing I see is that you could get rid of the Remove-Item calls on lines 115, 117, and 119 since you're now deleting the entire temp folder.

Fixed! Awesome feedback! :heart_eyes:

**Pull request merged**
